services:
  nuxt:
    build: .
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000" ]
      interval: 60s
      timeout: 5s
      retries: 3
